import { prisma } from './db';

/**
 * Ensure a user exists with an associated tenant. If user is new, create a tenant and
 * set the user as ADMIN of that tenant. Returns the tenantId and user id.
 */
export async function ensureUserAndTenant(params: {
  userId: string;
  email: string;
  tenantName?: string;
}) {
  const { userId, email, tenantName } = params;

  // If user already exists, just return their tenant
  const existing = await prisma.user.findUnique({ where: { id: userId } });
  if (existing) {
    return { tenantId: existing.tenantId, userId: existing.id };
  }

  // Create tenant and user transactionally
  const result = await prisma.$transaction(async (tx) => {
    const tenant = await tx.tenant.create({
      data: {
        name: tenantName ?? (email.split('@')[1] || 'default'),
        plan: 'free',
      },
    });

    const user = await tx.user.create({
      data: {
        id: userId,
        email,
        password: 'supabase-user', // placeholder; Supabase manages auth
        role: 'ADMIN',
        tenantId: tenant.id,
      },
    });

    return { tenantId: tenant.id, userId: user.id };
  });

  return result;
}

/**
 * Invite a user to an existing tenant. This creates a DB user row with MEMBER role.
 * In a full Supabase setup you'd also send an invite email via the Admin API.
 */
export async function inviteUserToTenant(params: {
  tenantId: string;
  email: string;
}) {
  const { tenantId, email } = params;

  // Create application user record. ID will be generated by DB (uuid())
  const user = await prisma.user.create({
    data: {
      email,
      password: 'invited-user', // placeholder; actual auth handled by Supabase
      role: 'MEMBER',
      tenantId,
    },
  });

  return user;
}
